controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login_check:
    path: /login_check
    controller: App\Controller\LoginController::loginCheck
